#!/usr/bin/env python3
"""
Phase 1 Module: Visualization Engine (F3)

Lightweight visualization engine for executing ActionPlans.
This is a placeholder implementation - full post-processing engine is Phase 2.

Key Features:
- Execute ActionPlan generated by NL Postprocess Executor
- Generate plot file paths (placeholder)
- Extract section data (placeholder)
- Calculate metrics (placeholder)
- Support for both OpenFOAM and generic solvers
"""

from __future__ import annotations

import os
import time
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from knowledge_compiler.phase1.nl_postprocess import (
    ActionPlan,
    ActionLog,
    ActionType,
)
from knowledge_compiler.phase1.schema import ResultManifest, ResultAsset


# ============================================================================
# Visualization Result
# ============================================================================

class OutputFormat(Enum):
    """Output format types"""
    PNG = "png"
    SVG = "svg"
    PDF = "pdf"
    VTK = "vtk"  # VTK format for ParaView
    CSV = "csv"  # CSV for data export
    JSON = "json"


@dataclass
class VisualizationResult:
    """
    Result of a single visualization action

    Contains the output file path and metadata.
    """
    action_index: int
    action_type: ActionType
    output_path: str
    output_format: OutputFormat
    success: bool
    metadata: Dict[str, Any] = field(default_factory=dict)
    error_message: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        return {
            "action_index": self.action_index,
            "action_type": self.action_type.value,
            "output_path": self.output_path,
            "output_format": self.output_format.value,
            "success": self.success,
            "metadata": self.metadata,
            "error_message": self.error_message,
        }


# ============================================================================
# Visualization Engine
# ============================================================================

class VisualizationEngine:
    """
    Phase 1 Visualization Engine

    Lightweight engine for executing ActionPlans. Supports both MOCK mode
    for testing and real matplotlib-based visualization.

    Supported Operations:
    - GENERATE_PLOT: Generate contour/vector/streamline plots
    - EXTRACT_SECTION: Extract section data (mock)
    - CALCULATE_METRIC: Calculate and output metrics
    - COMPARE_DATA: Generate comparison bar charts
    - REORDER_CONTENT: Reorder report structure
    """

    def __init__(
        self,
        output_root: Optional[str] = None,
        is_mock: bool = True,
    ):
        """
        Initialize visualization engine

        Args:
            output_root: Root directory for output files
            is_mock: If True, use placeholder mode (default for tests).
                    If False, use real matplotlib backend.
        """
        self.output_root = Path(output_root) if output_root else Path("outputs")
        self.is_mock = is_mock

        # Check matplotlib availability for real mode
        if not self.is_mock:
            try:
                import matplotlib
                matplotlib.use('Agg')  # Non-interactive backend
                import matplotlib.pyplot as plt
                import numpy as np
                self._plt = plt
                self._np = np
            except ImportError as e:
                raise ImportError(
                    f"Real visualization mode requires matplotlib and numpy: {e}"
                )

        # Plot type to format mapping
        self._plot_formats = {
            "contour": OutputFormat.PNG,
            "line": OutputFormat.PNG,
            "vector": OutputFormat.PNG,
            "streamline": OutputFormat.PNG,
        }

        # Metric type to calculation mapping
        self._metric_calculators = {
            "drag_coefficient": self._calc_drag_coefficient,
            "lift_coefficient": self._calc_lift_coefficient,
            "pressure_drop": self._calc_pressure_drop,
            "max_value": self._calc_max_value,
            "min_value": self._calc_min_value,
            "average": self._calc_average,
        }

    def execute_action_plan(
        self,
        action_plan: ActionPlan,
        manifest: ResultManifest,
        case_name: Optional[str] = None,
    ) -> ActionLog:
        """
        Execute an ActionPlan

        Args:
            action_plan: ActionPlan to execute
            manifest: ResultManifest with available resources
            case_name: Optional case name for output paths

        Returns:
            ActionLog with execution results
        """
        log = ActionLog(
            timestamp=time.time(),
            action_plan=action_plan,
        )

        # Check if plan is executable
        if not action_plan.is_executable():
            log.errors.append(
                f"Cannot execute: missing assets {action_plan.missing_assets}"
            )
            return log

        # Create output directory
        case_output_dir = self._create_output_dir(case_name or manifest.case_name)

        # Execute each action
        for i, action in enumerate(action_plan.actions):
            try:
                result = self._execute_action(
                    action,
                    i,
                    manifest,
                    case_output_dir,
                )

                # Convert VisualizationResult to dict for ActionLog
                log.add_result(i, result.to_dict())

                if not result.success:
                    log.errors.append(
                        f"Action {i} failed: {result.error_message}"
                    )

            except Exception as e:
                log.errors.append(f"Action {i} exception: {e}")
                log.add_result(i, {
                    "action_index": i,
                    "action_type": action.action_type.value,
                    "success": False,
                    "error_message": str(e),
                })

        return log

    def _execute_action(
        self,
        action: Action,
        index: int,
        manifest: ResultManifest,
        output_dir: Path,
    ) -> VisualizationResult:
        """Execute a single action"""
        action_type = action.action_type

        if action_type == ActionType.GENERATE_PLOT:
            return self._execute_generate_plot(action, index, manifest, output_dir)
        elif action_type == ActionType.EXTRACT_SECTION:
            return self._execute_extract_section(action, index, manifest, output_dir)
        elif action_type == ActionType.CALCULATE_METRIC:
            return self._execute_calculate_metric(action, index, manifest, output_dir)
        elif action_type == ActionType.COMPARE_DATA:
            return self._execute_compare_data(action, index, manifest, output_dir)
        elif action_type == ActionType.REORDER_CONTENT:
            return self._execute_reorder_content(action, index, output_dir)
        else:
            return VisualizationResult(
                action_index=index,
                action_type=action_type,
                output_path="",
                output_format=OutputFormat.PNG,
                success=False,
                error_message=f"Unknown action type: {action_type}",
            )

    def _execute_generate_plot(
        self,
        action: Action,
        index: int,
        manifest: ResultManifest,
        output_dir: Path,
    ) -> VisualizationResult:
        """Execute GENERATE_PLOT action"""
        params = action.parameters

        # Extract parameters
        field = params.get("field", "magnitude")
        plot_type = params.get("plot_type", "contour")
        plane = params.get("plane", "")
        colormap = params.get("colormap", "viridis")
        value_range = params.get("range", "auto")

        # Generate output filename
        filename = self._generate_plot_filename(field, plot_type, plane, index)
        output_path = output_dir / filename
        output_format = self._plot_formats.get(plot_type, OutputFormat.PNG)

        # Find source asset
        source_asset = self._find_source_asset(field, manifest)

        if self.is_mock:
            # MOCK mode: create placeholder
            self._create_placeholder_file(output_path, output_format)
            success = True
            error_msg = None
        else:
            # Real mode: use matplotlib
            try:
                success, error_msg = self._generate_plot_real(
                    output_path, plot_type, field, colormap, value_range
                )
            except Exception as e:
                success = False
                error_msg = str(e)

        return VisualizationResult(
            action_index=index,
            action_type=ActionType.GENERATE_PLOT,
            output_path=str(output_path),
            output_format=output_format,
            success=success,
            error_message=error_msg,
            metadata={
                "field": field,
                "plot_type": plot_type,
                "plane": plane,
                "source_asset": source_asset,
                "colormap": colormap,
                "range": value_range,
                "mode": "mock" if self.is_mock else "real",
            },
        )

    def _execute_extract_section(
        self,
        action: Action,
        index: int,
        manifest: ResultManifest,
        output_dir: Path,
    ) -> VisualizationResult:
        """Execute EXTRACT_SECTION action"""
        params = action.parameters

        plane = params.get("plane", "auto")
        field = params.get("field", "magnitude")

        # Generate output filename
        filename = f"section_{plane}_{field}_{index:03d}.vtk"
        output_path = output_dir / filename

        # Create placeholder VTK file
        self._create_placeholder_file(output_path, OutputFormat.VTK)

        source_asset = self._find_source_asset(field, manifest)

        return VisualizationResult(
            action_index=index,
            action_type=ActionType.EXTRACT_SECTION,
            output_path=str(output_path),
            output_format=OutputFormat.VTK,
            success=True,
            metadata={
                "plane": plane,
                "field": field,
                "source_asset": source_asset,
            },
        )

    def _execute_calculate_metric(
        self,
        action: Action,
        index: int,
        manifest: ResultManifest,
        output_dir: Path,
    ) -> VisualizationResult:
        """Execute CALCULATE_METRIC action"""
        params = action.parameters

        metric_type = params.get("metric_type", "value")
        location = params.get("location", "")

        # Get calculator
        calculator = self._metric_calculators.get(
            metric_type,
            lambda *args: {"value": 0.0, "unit": "unknown"}
        )

        # Calculate (placeholder - actual calc in Phase 2)
        result = calculator(params, manifest)

        # Generate output filename
        filename = f"metric_{metric_type}"
        if location:
            filename += f"_{location}"
        filename += f"_{index:03d}.json"

        output_path = output_dir / filename

        # Write result to JSON
        import json
        with open(output_path, 'w') as f:
            json.dump(result, f, indent=2)

        return VisualizationResult(
            action_index=index,
            action_type=ActionType.CALCULATE_METRIC,
            output_path=str(output_path),
            output_format=OutputFormat.JSON,
            success=True,
            metadata={
                "metric_type": metric_type,
                "location": location,
                "result": result,
            },
        )

    def _execute_compare_data(
        self,
        action: Action,
        index: int,
        manifest: ResultManifest,
        output_dir: Path,
    ) -> VisualizationResult:
        """Execute COMPARE_DATA action"""
        params = action.parameters

        items = params.get("items", [])
        field = params.get("field", "magnitude")

        # Generate output filename
        items_str = "_vs_".join(items)
        filename = f"comparison_{field}_{items_str}_{index:03d}.png"
        output_path = output_dir / filename

        if self.is_mock:
            # MOCK mode: create placeholder
            self._create_placeholder_file(output_path, OutputFormat.PNG)
            success = True
            error_msg = None
        else:
            # Real mode: use matplotlib
            try:
                success, error_msg = self._generate_comparison_real(
                    output_path, items, field
                )
            except Exception as e:
                success = False
                error_msg = str(e)

        return VisualizationResult(
            action_index=index,
            action_type=ActionType.COMPARE_DATA,
            output_path=str(output_path),
            output_format=OutputFormat.PNG,
            success=success,
            error_message=error_msg,
            metadata={
                "items": items,
                "field": field,
                "comparison_type": params.get("comparison_type", "side_by_side"),
                "mode": "mock" if self.is_mock else "real",
            },
        )

    def _execute_reorder_content(
        self,
        action: Action,
        index: int,
        output_dir: Path,
    ) -> VisualizationResult:
        """Execute REORDER_CONTENT action"""
        params = action.parameters

        sequence = params.get("sequence", [])

        # Generate output filename
        filename = f"report_order_{index:03d}.json"
        output_path = output_dir / filename

        # Write order to JSON
        import json
        with open(output_path, 'w') as f:
            json.dump({"sequence": sequence}, f, indent=2)

        return VisualizationResult(
            action_index=index,
            action_type=ActionType.REORDER_CONTENT,
            output_path=str(output_path),
            output_format=OutputFormat.JSON,
            success=True,
            metadata={
                "sequence": sequence,
                "num_items": len(sequence),
            },
        )

    # ========================================================================
    # Real Visualization Methods (matplotlib backend)
    # ========================================================================

    def _generate_plot_real(
        self,
        output_path: Path,
        plot_type: str,
        field: str,
        colormap: str,
        value_range: str,
    ) -> Tuple[bool, Optional[str]]:
        """
        Generate a real plot using matplotlib

        Returns:
            Tuple of (success, error_message)
        """
        plt = self._plt
        np = self._np

        # Create sample data for demonstration
        # In production, this would load actual CFD data
        x = np.linspace(0, 1, 100)
        y = np.linspace(0, 1, 100)
        X, Y = np.meshgrid(x, y)

        # Generate synthetic field data based on field type
        if field in ("pressure", "p"):
            Z = 101325 + 1000 * np.sin(2 * np.pi * X) * np.cos(2 * np.pi * Y)
        elif field in ("velocity", "U", "magnitude"):
            Z = 10 * (X**2 + Y**2)
        elif field in ("temperature", "T"):
            Z = 300 + 50 * X * Y
        else:
            Z = np.random.rand(100, 100)

        try:
            fig, ax = plt.subplots(figsize=(10, 8))

            if plot_type == "contour":
                # Filled contour plot
                levels = self._get_levels(value_range, Z)
                cf = ax.contourf(X, Y, Z, levels=levels, cmap=colormap)
                fig.colorbar(cf, ax=ax, label=field)
                ax.set_title(f"{field.capitalize()} Contour")
                ax.set_xlabel("x")
                ax.set_ylabel("y")

            elif plot_type == "line":
                # Line plot (extract along middle)
                mid_idx = len(y) // 2
                ax.plot(x, Z[mid_idx, :], linewidth=2)
                ax.set_title(f"{field.capitalize()} Profile (y=0.5)")
                ax.set_xlabel("x")
                ax.set_ylabel(field)
                ax.grid(True, alpha=0.3)

            elif plot_type == "vector":
                # Vector quiver plot
                skip = 5  # Skip points for cleaner display
                U = Z * np.cos(np.pi * X)
                V = Z * np.sin(np.pi * Y)
                ax.quiver(
                    X[::skip, ::skip],
                    Y[::skip, ::skip],
                    U[::skip, ::skip],
                    V[::skip, ::skip],
                    Z[::skip, ::skip],
                    cmap=colormap,
                )
                ax.set_title(f"{field.capitalize()} Vector Field")
                ax.set_xlabel("x")
                ax.set_ylabel("y")

            elif plot_type == "streamline":
                # Streamline plot
                U = Z * np.cos(np.pi * X)
                V = Z * np.sin(np.pi * Y)
                strm = ax.streamplot(
                    X, Y, U, V,
                    color=Z,
                    cmap=colormap,
                    linewidth=1,
                    arrowsize=1.5,
                )
                fig.colorbar(strm.lines, ax=ax, label=field)
                ax.set_title(f"{field.capitalize()} Streamlines")
                ax.set_xlabel("x")
                ax.set_ylabel("y")

            else:
                # Default contour
                ax.contourf(X, Y, Z, cmap=colormap)
                ax.set_title(f"{field.capitalize()} ({plot_type})")

            plt.tight_layout()
            output_path.parent.mkdir(parents=True, exist_ok=True)
            plt.savefig(output_path, dpi=150, bbox_inches='tight')
            plt.close(fig)

            return True, None

        except Exception as e:
            plt.close('all')
            return False, f"Plot generation failed: {e}"

    def _get_levels(self, value_range: str, data) -> int:
        """Get number of contour levels based on range setting"""
        if value_range == "auto":
            return 20
        elif value_range == "fine":
            return 50
        elif value_range == "coarse":
            return 10
        else:
            return 20

    def _generate_comparison_real(
        self,
        output_path: Path,
        items: List[str],
        field: str,
    ) -> Tuple[bool, Optional[str]]:
        """
        Generate a real comparison bar chart using matplotlib

        Returns:
            Tuple of (success, error_message)
        """
        plt = self._plt
        np = self._np

        try:
            # Generate synthetic comparison data
            np.random.seed(42)
            values = np.random.rand(len(items)) * 100

            fig, ax = plt.subplots(figsize=(10, 6))
            bars = ax.bar(items, values, color='steelblue', edgecolor='navy')

            # Add value labels on bars
            for bar, val in zip(bars, values):
                height = bar.get_height()
                ax.text(
                    bar.get_x() + bar.get_width() / 2.,
                    height,
                    f'{val:.1f}',
                    ha='center',
                    va='bottom',
                )

            ax.set_title(f"{field.capitalize()} Comparison")
            ax.set_ylabel(field)
            ax.set_xlabel("Items")
            ax.grid(axis='y', alpha=0.3)
            plt.tight_layout()

            output_path.parent.mkdir(parents=True, exist_ok=True)
            plt.savefig(output_path, dpi=150, bbox_inches='tight')
            plt.close(fig)

            return True, None

        except Exception as e:
            plt.close('all')
            return False, f"Comparison generation failed: {e}"

    # ========================================================================
    # Helper Methods
    # ========================================================================

    def _create_output_dir(self, case_name: str) -> Path:
        """Create output directory for case"""
        output_dir = self.output_root / case_name / "visualizations"
        output_dir.mkdir(parents=True, exist_ok=True)
        return output_dir

    def _generate_plot_filename(
        self,
        field: str,
        plot_type: str,
        plane: str,
        index: int,
    ) -> str:
        """Generate plot filename"""
        parts = [plot_type, field]
        if plane:
            parts.append(plane)
        parts.append(f"{index:03d}")
        return "_".join(parts) + ".png"

    def _find_source_asset(self, field: str, manifest: ResultManifest) -> Optional[str]:
        """Find source asset for a field"""
        field_to_asset = {
            "pressure": "p",
            "velocity": "U",
            "temperature": "T",
            "k": "k",
            "magnitude": "U",
        }

        asset_name = field_to_asset.get(field, field)

        for asset in manifest.assets:
            if asset_name in asset.path.lower():
                return asset.path

        return None

    def _create_placeholder_file(self, path: Path, format_type: OutputFormat) -> None:
        """Create a placeholder file"""
        if format_type == OutputFormat.JSON:
            import json
            with open(path, 'w') as f:
                json.dump({"placeholder": True}, f)
        else:
            # Create empty file
            path.parent.mkdir(parents=True, exist_ok=True)
            path.touch()

    # ========================================================================
    # Metric Calculators
    # ========================================================================

    def _calc_drag_coefficient(self, params: Dict, manifest: ResultManifest) -> Dict:
        """Calculate drag coefficient"""
        if self.is_mock:
            return {"value": 0.0, "unit": "-", "coefficient_type": "drag"}

        # Real calculation: try to read from OpenFOAM forceCoeffs
        result_root = manifest.result_root if manifest else None
        if result_root:
            coeffs_file = Path(result_root) / "postProcessing" / "forceCoeffs" / "0" / "coefficient.dat"
            if coeffs_file.exists():
                try:
                    import numpy as np
                    # Read OpenFOAM forceCoeffs output
                    data = np.loadtxt(coeffs_file, skiprows=1)  # Skip header
                    if len(data) > 0:
                        # Cd is typically column 1 (Time, Cd, Cl, Cm)
                        cd = data[-1, 1] if data.shape[1] > 1 else 0.0
                        return {
                            "value": float(cd),
                            "unit": "-",
                            "coefficient_type": "drag",
                            "source": "forceCoeffs",
                        }
                except Exception:
                    pass

        # Fallback: synthetic value
        return {"value": 0.025, "unit": "-", "coefficient_type": "drag", "source": "synthetic"}

    def _calc_lift_coefficient(self, params: Dict, manifest: ResultManifest) -> Dict:
        """Calculate lift coefficient"""
        if self.is_mock:
            return {"value": 0.0, "unit": "-", "coefficient_type": "lift"}

        # Real calculation: try to read from OpenFOAM forceCoeffs
        result_root = manifest.result_root if manifest else None
        if result_root:
            coeffs_file = Path(result_root) / "postProcessing" / "forceCoeffs" / "0" / "coefficient.dat"
            if coeffs_file.exists():
                try:
                    import numpy as np
                    data = np.loadtxt(coeffs_file, skiprows=1)
                    if len(data) > 0 and data.shape[1] > 2:
                        cl = data[-1, 2]  # Cl is column 2
                        return {
                            "value": float(cl),
                            "unit": "-",
                            "coefficient_type": "lift",
                            "source": "forceCoeffs",
                        }
                except Exception:
                    pass

        return {"value": 0.15, "unit": "-", "coefficient_type": "lift", "source": "synthetic"}

    def _calc_pressure_drop(self, params: Dict, manifest: ResultManifest) -> Dict:
        """Calculate pressure drop"""
        if self.is_mock:
            return {"value": 0.0, "unit": "Pa", "metric_type": "pressure_drop"}

        # Try to calculate from field data
        result_root = manifest.result_root if manifest else None
        if result_root:
            # Look for pressure field
            p_file = Path(result_root) / "0" / "p"
            if not p_file.exists():
                p_file = Path(result_root) / "0.5" / "p"  # Try mid-time

            if p_file.exists():
                try:
                    # Would parse OpenFOAM file here
                    # For now, return synthetic value
                    return {
                        "value": 150.5,
                        "unit": "Pa",
                        "metric_type": "pressure_drop",
                        "source": "synthetic",
                    }
                except Exception:
                    pass

        return {"value": 100.0, "unit": "Pa", "metric_type": "pressure_drop", "source": "synthetic"}

    def _calc_max_value(self, params: Dict, manifest: ResultManifest) -> Dict:
        """Calculate maximum value"""
        if self.is_mock:
            return {"value": 0.0, "unit": "unknown", "metric_type": "max"}

        if not self.is_mock and hasattr(self, '_np'):
            # Generate synthetic max from sample data
            np = self._np
            sample_data = np.random.randn(1000) * 10 + 50
            return {
                "value": float(np.max(sample_data)),
                "unit": "unknown",
                "metric_type": "max",
                "source": "synthetic",
            }

        return {"value": 0.0, "unit": "unknown", "metric_type": "max"}

    def _calc_min_value(self, params: Dict, manifest: ResultManifest) -> Dict:
        """Calculate minimum value"""
        if self.is_mock:
            return {"value": 0.0, "unit": "unknown", "metric_type": "min"}

        if not self.is_mock and hasattr(self, '_np'):
            np = self._np
            sample_data = np.random.randn(1000) * 10 + 50
            return {
                "value": float(np.min(sample_data)),
                "unit": "unknown",
                "metric_type": "min",
                "source": "synthetic",
            }

        return {"value": 0.0, "unit": "unknown", "metric_type": "min"}

    def _calc_average(self, params: Dict, manifest: ResultManifest) -> Dict:
        """Calculate average value"""
        if self.is_mock:
            return {"value": 0.0, "unit": "unknown", "metric_type": "average"}

        if not self.is_mock and hasattr(self, '_np'):
            np = self._np
            sample_data = np.random.randn(1000) * 10 + 50
            return {
                "value": float(np.mean(sample_data)),
                "unit": "unknown",
                "metric_type": "average",
                "source": "synthetic",
            }

        return {"value": 0.0, "unit": "unknown", "metric_type": "average"}


# ============================================================================
# Convenience Functions
# ============================================================================

def execute_visualization(
    action_plan: ActionPlan,
    manifest: ResultManifest,
    output_root: Optional[str] = None,
    case_name: Optional[str] = None,
    is_mock: bool = True,
) -> ActionLog:
    """
    Convenience function to execute visualization

    Args:
        action_plan: ActionPlan to execute
        manifest: ResultManifest with available resources
        output_root: Optional output root directory
        case_name: Optional case name
        is_mock: If True, use placeholder mode (default for tests).
                If False, use real matplotlib backend.

    Returns:
        ActionLog with execution results
    """
    engine = VisualizationEngine(output_root=output_root, is_mock=is_mock)
    return engine.execute_action_plan(action_plan, manifest, case_name)


# ============================================================================
# Export
# ============================================================================

__all__ = [
    "OutputFormat",
    "VisualizationResult",
    "VisualizationEngine",
    "execute_visualization",
]
